import React, {useEffect, useState} from 'react'
import { useSelector, useDispatch } from 'react-redux'
import {PRIVILEGE,PRIVILEGE_TYPED} from '../../app/util/index.js'
import { connect } from 'react-redux'
import { useNavigate } from 'react-router-dom'
import { getAllUsersAndSitesAsync, getAllSitesByUserAsync } from '../../app/slice/usersites'
import {deleteUser} from '../../app/slice/user'
import '../style/useradmin.css'
import AddUserForm from './addUserForm.js'
import EditUserForm from './editUserForm.js'

